<?php
/**
 * Created by PhpStorm.
 * User: Dymko
 * Date: 8/17/16
 * Time: 8:09 PM
 */

namespace Kaktus\Tests;

use Kaktus\Crouton\Crouton;
use Kaktus\Crouton\Crud\Write;

class CroutonTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if(!file_exists('/tmp/crouton'))
        {
            $fh = fopen('/tmp/crouton', 'w') or die("Can't create file");
            chmod('/tmp/crouton', 0777);
            fwrite($fh, "#Crouton Cron Entry\n");
        }

    }

    public function testWrite()
    {

        $crouton = new Crouton();
        $crouton->write('TestWrite', '1', "12:34", "18:21", "/tmp/crouton", '/tmp/crouton');

        $write = new Write('/tmp/crouton');
        $cron = $write->cron_creator('1', "12:34", "18:21", "/tmp/crouton");

        $handle = fopen('/tmp/crouton','r');
        $data = fread($handle,filesize('/tmp/crouton'));

        $cron = preg_replace('/\*/', '\*', $cron);
        $cron = preg_replace('/\//', '\/', $cron);
        $cron = "/$cron/";

        $this->assertRegExp($cron, $data);

    }

    public function testDelete()
    {
        $crouton = new Crouton();
        $crouton->write('TestDeleteCrouton', '1', "12:34", "18:21", "/tmp/crouton", '/tmp/crouton');

        $crouton->delete('/tmp/crouton', 'TestDeleteCrouton');

        $data = file('/tmp/crouton');

        foreach($data as $line) {
            if(trim("#TestDeleteCrouton") == $line)
            {
                $this->assertFalse(true);
            }
            else
            {
                $this->assertTrue(true);
            }

        }
    }

    public function testCronCreator()
    {
        $crouton = new Write('/tmp/crouton');
        $cron_test = $crouton->cron_creator('1,4,5,7', "02:34", "12:12", "/tmp/crouton");
        $cron_test = preg_replace('/\*/', '\*', $cron_test);
        $cron_test = preg_replace('/\//', '\/', $cron_test);
        $cron_test = "/$cron_test/";

        $this->assertRegExp($cron_test, '5 02-12 * * 1,4,5,7 /tmp/crouton');


        $cron_test = $crouton->cron_creator('1,4,5,7', "02:34", "12:12", "/tmp/crouton", "php");
        $cron_test = preg_replace('/\*/', '\*', $cron_test);
        $cron_test = preg_replace('/\//', '\/', $cron_test);
        $cron_test = "/$cron_test/";

        $this->assertRegExp($cron_test, '5 02-12 * * 1,4,5,7 php /tmp/crouton');

    }
}